
=== Common Dialogs
[small]#Rfr: link:++http://www.fltk.org/doc-1.3/group__group__comdlg.html++[Common Dialogs classes functions].#

* *fl.alert*(_message_)

* *fl.beep*(<<beep, _beep_>>)

* *fl.color_chooser_b*(_label_, _r_, _g_, _b_, [<<colorchoosermode, _colorchoosermode_>>]) +
_r_, _g_, _b_ = *fl.color_chooser_f*(_label_, _r_, _g_, _b_, [<<colorchoosermode, _colorchoosermode_>>]) +
[small]#Returns _nil_ if the user cancelled the dialog. +
The '_b' version works with byte components (0 .. 255), while the '_f' version works with 
floating point components (0.0 .. 1.0).#

* _dirname_ = *fl.dir_chooser*(_message_, _dirname_, [_relative_]) +
[small]#Returns _nil_ if the user cancelled the dialog. +
_relative_: a boolean (_true_ for relative path return, _false_ for absolute path).#

* _filename_  = *fl.file_chooser*(_message_, _pattern_, _filename_, [_relative_]) +
[small]#Returns _nil_ if the user cancelled the dialog. +
_relative_: a boolean (_true_ for relative path return, _false_ for absolute path).#

* *fl.file_chooser_callback*([_func_]) +
[small]#If _func_ is _nil_ or none, unregisters the current file chooser callback (if any). +
The _func_ callback is executed as *func(filename)*.#

* *fl.file_chooser_ok_label*(_label_)

* *fl.message*(_message_) +
*fl.message_hotspot*(_boolean_) +
_boolean_ = *fl.message_hotspot*( )

* *fl.message_title*(_title_)

* *fl.message_title_default*(_title_)

* _text_  = *fl.password*(_message_, [_default_]) +
[small]#Returns _nil_ if the user cancelled the dialog.#


