
=== Handlers
[small]#Rfr: link:++http://www.fltk.org/doc-1.3/classFl.html++[Fl].#

==== Check handler

* _boolean_  = *fl.has_check*( ) +
[small]#Returns _true_ if the check handler is set and has not yet been
called, _false_ otherwise.#

* *fl.set_check*(_func_) +
[small]#Sets _func_ (a function) as the check handler. It will be executed
as *func()* (i.e. passing it no arguments). 
If called with no arguments, removes the handler.#

NOTE: There is a single check handler in MoonFLTK. If multiple
handlers are needed, multiplex it in Lua.


==== File descriptors handler

* _boolean_  = *fl.has_fd_handler*( ) +
[small]#Returns _true_ if the fd handler is set, _false_ otherwise.#

[[fl.set_fd_handler]]
* *fl.set_fd_handler*(_func_) +
[small]#Sets _func_ (a function) as the fd handler. It will be executed
as *func(fd)* where _fd_ is the affected file handler. 
If called with no arguments, removes the handler.#

NOTE: There is a single fd handler in MoonFLTK to handle all file
descriptors registered with <<fl.add_fd, fl.add_fd>>( ). +
The file descriptor for a Lua
http://www.lua.org/manual/5.3/manual.html#6.8[io library] file handle
can be obtained with the <<fl.fileno, fl.fileno>>( ) function.

[[fl.add_fd]]
* *fl.add_fd*(_fd_, <<whenfd, _whenfd_>>) +
[small]#Monitor the file descriptor _fd_. When the file descriptor is ready
(depending on the _whenfd_ argument) the <<fl.set_fd_handler, fd handler>> is executed.#

* *fl.remove_fd*(_fd_) +
[small]#Stop monitoring the file descriptor _fd_.#


==== Idle handler

* _boolean_  = *fl.has_idle*( ) +
[small]#Returns _true_ if the idle handler is set, _false_ otherwise.#

* *fl.set_idle*(_func_) +
[small]#Sets _func_ (a function) as the idle handler. It will be executed
as *func()*(i.e. passing it no arguments).
If called with no arguments, removes the handler.#

NOTE: There is a single idle handler in MoonFLTK. If multiple
handlers are needed, multiplex it in Lua.

==== Timeout handler

* _boolean_  = *fl.has_timeout*( ) +
[small]#Returns _true_ if the timeout handler is set, _false_ otherwise#.

[[fl.set_timeout]]
* *fl.set_timeout*(_seconds_, _repeat_, _func_) +
[small]#Sets the timer so to expire after _seconds_.
At the timer expiration, the _func_ callback will be executed as *func()*
(passing it no arguments).
If _repeat_ is _true_, the timer is automatically restarted at its expiration.
If called with no arguments, this function stops the timer and unregisters the callback.#

NOTE: There is a single timeout handler in MoonFLTK. If multiple
concurrent timers are needed, the <<moonfltk.timer, *moonfltk.timer*>> 
module can be used to multiplex it.


[[moonfltk.timer]]
==== moonfltk.timer module

MoonFLTK comes with an optional Lua module, named *moonfltk.timer*, that 
uses the single <<fl.set_timeout, timeout handler>> to implement a timer heap.
The following example shows how to use it.

.moonfltk.timer example
[source,lua]
----
fl = require("moonfltk")
timer = require("moonfltk.timer")

-- Init the timer module
timer.init()

tname = {}  -- tname[tid] = timer name
tstart = {} -- tstart[tid] = starting time 

-- Callback for timers' expiration:
function texpired(tid)
   local now = fl.gettime()
   print(string.format("timer %s expired (elapsed time: %g seconds)", 
          tname[tid], now - tstart[tid]))
   -- restart timer:
   tstart[tid] = timer.start(tid)
end

-- Create a few timers:
t1 = timer.create(2, texpired)
tname[t1] = "T1"
t2 = timer.create(3.1, texpired)
tname[t2] = "T2"

-- Start them:
tstart[t1], errmsg = timer.start(t1)
tstart[t2], errmsg = timer.start(t2)

-- Enter the FLTK main loop:
while true do
   fl.wait(0)
end
----

The *moonfltk.timer* module provides the functions described below. Time
values are obtained with the <<fl.gettime, fl.gettime>>( ) function. 
On error, all these functions return _nil_ followed by an error message.

* *timer.init*( ) +
[small]#Inits the module.#

* _tid_  = *timer.create*(_timeout_, _func_) +
[small]#Creates a new timer and returns a unique timer identifier (_tid_) for
subsequent operations. 
The _timeout_ argument is the default timeout in seconds, which will be used
to compute the expiration time if it is not specified when the timer is started.
The _func_ argument (a function) is the callback that will be executed
as *func(tid)* at timer expiration.#

* *timer.delete*(_tid_) +
[small]#Deletes the timer identified by _tid_.#

* *timer.deleteall*( ) +
[small]#Deletes all the timers.#

* _startime_  = *timer.start*(_tid_, [_exptime_]) +
[small]#Starts the timer identified by _tid_ so to expire at the time 
_exptime_.#

* *timer.stop*(_tid_) +
[small]#Stops the timer identified by _tid_.#

* _timeut_  = *timer.timeout*(_tid_, [_timeout_]) +
[small]#Gets/sets the default timeout (in seconds) for the timer identified by _tid_.#

* _func_  = *timer.callback*(_tid_, [_func_]) +
[small]#Gets/sets the callback for the timer identified by _tid_.#

* _boolean_, _exptime_ = *timer.isrunning*(_tid_) +
[small]#If the timer is running, returns _true_ and the expiration time,
otherwise returns _false_.#


