
== Preface

This is the reference manual of *MoonFLTK*, which is a 
http://www.lua.org[*Lua*] binding library for the
http://www.fltk.org/index.php[*Fast Light Toolkit (FLTK)*]. 
footnote:[
This manual is written in
http://www.methods.co.nz/asciidoc/[AsciiDoc], rendered with
http://asciidoctor.org/[AsciiDoctor] and a CSS from the
https://github.com/asciidoctor/asciidoctor-stylesheet-factory[AsciiDoctor Stylesheet Factory].
The PDF version is produced with
https://github.com/asciidoctor/asciidoctor-pdf[AsciiDoctor-Pdf].]

It is assumed that the reader is familiar with both FLTK and the Lua programming language.

For convenience of reference, this document contains external (deep) links to the 
http://www.lua.org/manual/5.3/manual.html[Lua Reference Manual] and the 
http://www.fltk.org/doc-1.3/index.html[FLTK Programming Manual].

=== Getting and installing

For installation intructions, refer to the README file in the 
https://github.com/stetre/moonfltk[*MoonFLTK official repository*]
on GitHub.

////
MoonFLTK runs on GNU/Linux and requires 
*http://www.lua.org[Lua]* version 5.3 or greater, and
*http://www.fltk.org/software.php[FLTK]* version 1.3.3 or greater.

To install MoonFLTK, download the 
https://github.com/stetre/moonfltk/releases[latest release] and do the following:

[source,shell]
----
# ... download moonfltk-0.1.tar.gz ...
[ ]$ tar -zxpvf moonfltk-0.1.tar.gz
[ ]$ cd moonfltk-0.1
[moonfltk-0.1]$ make
[moonfltk-0.1]$ sudo make install
----

By default, MoonFLTK installs its components in subdirectories of `/usr/local/`
(and creates such directories, if needed).
This behaviour can be changed by defining PREFIX with the desired alternative 
base installation directory. For example, this will install the components
in `/home/joe/local`:

[source,shell]
----
[moonfltk-0.1]$ make
[moonfltk-0.1]$ make install PREFIX=/home/joe/local
----

==== Compiling without OpenGL and images. 

By default, the above procedure compiles the full MoonFLTK library, with support for
both OpenGL and images. It also assumes that the corresponding FLTK libraries (and
dependencies) are installed on your system.

If this is not the case, or if you don't want or need support for OpenGL and/or
images, you can compile with the *no-gl* and/or *no-images* switches set, as in the
following example:

----
# exclude support for OpenGL and images:
[moonfltk-0.1]$ make no-gl=1 no-images=1
[moonfltk-0.1]$ make check
[moonfltk-0.1]$ sudo make install
----
////

=== Module organization

The MoonFLTK module is loaded using Lua's 
http://www.lua.org/manual/5.3/manual.html#pdf-require[require]() and
returns a table containing the functions it provides 
(as usual with Lua modules). This manual assumes that such
table is named *fl*, i.e. that it is loaded with:

[source,lua,indent=1]
----
fl = require("moonfltk")
----

but nothing forbids the use of a different name.

=== Examples

Examples can be found in the *examples/* directory of the release package
(the *examples/fltk* subdirectory contains portings to MoonFLTK of most of the examples
that come with the FLTK distribution).

=== License

MoonFLTK is released under the *MIT/X11 license* (same as
http://www.lua.org/license.html[Lua], and with the same only requirement to give proper
credits to the original author). 
The copyright notice is in the LICENSE file in the base directory
of the https://github.com/stetre/moonfltk[official repository] on GitHub.

<<<
