
[[text_display]]
==== text_display
[small]#Rfr: link:++http://www.fltk.org/doc-1.3/classFl__Text__Display.html++[Fl_Text_Display]. +
Inherits from: <<widget, widget>>, <<group, group>>.#


IMPORTANT: See <<text_buffer, text_buffer>> indexing.


* _text_display_ = *fl.text_display*(_x_, _y_, _w_, _h_, [_label_])


* *:buffer*(<<text_buffer, _text_buffer_>>)
<<text_buffer, _text_buffer_>> = *:buffer*( )

* _nlines_ = *:count_lines*(_start_, [_end_], [_islinestart_])


* *:cursor_color*(<<color, _color_>>) +
<<color, _color_>> = *:cursor_color*( )

* *:cursor_style*(<<cursorstyle,_cursorstyle_>>)

* *:hide_cursor*( )

* *:highlight_data*(_stylebuffer_, _styletable_, [_unfinishedstyle_, _func_]) +
[small]#_stylebuffer_: a <<text_buffer, _text_buffer_>>. +
_styletable_: an array (integer-indexed table) of style-describing arrays, each of which in the
form: *{ color, font, fontsize, fontattr }* (_fontattr_ is optional and defaults to 0). 
Characters in the _stylebuffer_ indicate styles in the _styletable_: 'A', denotes the first
style, 'B' the second, and so on (up to '~'). +
_unfinishedstyle_: (optional) the character denoting the unfinished style that triggers the 
callback below. +
_func_: (optional) callback triggered by _unfinishedstyle_. The callback is executed as
*func(text_display, pos)* where _text_display_ is this widget.#

* _boolean_ = *:in_selection*(_x_, _y_)


* *:insert*(_text_)

* *:insert_position*(_pos_) +
_pos_ = *:insert_position*( )


* _pos_ = *:line_end*(_pos_, [_islinestart_])


* _pos_ = *:line_start*(_pos_)


* *:linenumber_align*(<<alignment,_alignment_>>) +
<<alignment,_alignment_>> = *:linenumber_align*( )

* *:linenumber_bgcolor*(<<color, _color_>>) +
<<color, _color_>> = *:linenumber_bgcolor*( )

* *:linenumber_fgcolor*(<<color, _color_>>) +
<<color, _color_>> = *:linenumber_fgcolor*( )

* *:linenumber_font*(<<font,_font_>>) +
<<font,_font_>> = *:linenumber_font*( )

* *:linenumber_format*(_fmt_) +
_fmt_ = *:linenumber_format*( )


* *:linenumber_size*(_fontsize_) +
_fontsize_ = *:linenumber_size*( )

* *:linenumber_width*(_w_) +
_w_ = *:linenumber_width*( )

* _boolean_ = *:move_down*( ) +
_boolean_ = *:move_left*( ) +
_boolean_ = *:move_right*( ) +
_boolean_ = *:move_up*( )

* *:next_word*( )

* *:overstrike*( )

* _x_, _y_ = *:position_to_xy*(_pos_) +
[small]#Returns _nil_ if character is vertically out of view.#

* *:previous_word*( )

* *:redisplay_index*(_start_, _end_)

* _pos_ = *:rewind_lines*(_start_, _nlines_)


* *:scrollbar_align*(<<alignment,_alignment_>>) +
<<alignment,_alignment_>> = *:scrollbar_align*( )

* *:scrollbar_width*(_w_) +
_w_ = *:scrollbar_width*( )

* *:shortcut*(<<shortcut,_shortcut_>>) +
<<shortcut,_shortcut_>> = *:shortcut*( )

* *:show_cursor*(_boolean_)

* *:show_insert_position*( )

* _pos_ = *:skip_lines*(_start_, _nlines_, [_islinestart_])

* *:textcolor*(<<color, _color_>>) +
<<color, _color_>> = *:textcolor*( )

* *:textfont*(<<font,_font_>>) +
<<font,_font_>> = *:textfont*( )

* *:textsize*(_fontsize_) +
_fontsize_ = *:textsize*( )

* _end + 1_ = *:word_end*(_pos_)

* _start_ = *:word_start*(_pos_)

* *:wrap_mode*(<<wrapmode, _wrapmode_>>, _margin_)


