
[[tree]]
==== tree

[small]#Rfr: link:++http://www.fltk.org/doc-1.3/classFl__Tree.html++[Fl_Tree]. +
Inherits from: <<widget, widget>>, <<group, group>>. +
RTTI: see <<treeselect, _treeselect_>>.#

NOTE: In MoonFLTK, tree items are identified by their pathname and the tree they
belong to (orphaned items are not supported).
The link:++http://www.fltk.org/doc-1.3/classFl__Tree__Item.html++[Fl_Tree_Item] class
in not directly exposed, while its methods are exposed as methods of the <<tree, fl.tree>>
object (renamed with a leading *item_* prefix, and accepting the item's _pathname_
as first argument). Children items' indices are 1-based.

* _tree_ = *fl.tree*(_x_, _y_, _w_, _h_, [_label_])

* *:add*(_pathname_)

* *:argument*(_arg_) +
_arg_ + = *:argument*( ) +
[small]#_arg_: any Lua value.#

* *:callback*(_func_, [_arg_]) +
_func_ + = *:callback*( ) +
[small]#The _func_ callback (a Lua function) is executed as *func(tree, pathname, reason, arg)*,
where _pathname_ is the affected item and _reason_ is the reason for calling back
(see <<treereason, _treereason_>>). The optional argument _arg_ may be any Lua value.#

* *:clear*([_pathname_]) +
[small]#If _pathname_ is passed, clears the item's subtree, otherwise clears the whole tree.#

* *:closeicon*(<<image, _image_>>) +
<<image, _image_>> = *:closeicon*( )

* *:connectorcolor*(<<color, _color_>>) +
<<color, _color_>> = *:connectorcolor*( )

* *:connectorstyle*(<<treeconnector, _treeconnector_>>) +
<<treeconnector, _treeconnector_>> = *:connectorstyle*( )

* *:connectorwidth*(_pixels_) +
_pixels_ = *:connectorwidth*( )

* *:extend_selection_up*(_from_, _to_, [_op_], [_visible_]) +
_n_ = *:extend_selection_down*(_from_, _to_, [_op_], [_visible_]) +
[small]#_from_, _to_: items pathnames. +
_op_: '_select_' (default), '_deselect_', '_toggle_'. +
_visible_: boolean (default=_false_).#

* _pathname_ = *:first*( ) +
_pathname_ = *:first_selected_item*( ) +
_pathname_ = *:first_visible_item*( )

* _pathname_ = *:get_item_focus*( )


* *:hposition*(_h_) +
_h_ = *:hposition*( )


* _pathname_ = *:insert_above*(_above_, _name_) +
[small]#_above_: pathname of the item above which the new item has to be inserted. +
_name_: name of the new item. +
Returns the _pathname_ of the newly inserted item.#

* _pathname_  = *:insert*(_parent_, _name_, _index_) +
[small]#_parent_: pathname of the parent item. +
_name_: name of the new item. +
Returns the _pathname_ of the newly inserted item.#

* _boolean_ = *:is_hscroll_visible*( ) +
_boolean_ = *:is_vscroll_visible*( )

* *:labelmarginleft*(_pixels_) +
* _pixels_ = *:labelmarginleft*( )


* _pathname_ = *:last*( ) +
_pathname_ = *:last_selected_item*( ) +
_pathname_ = *:last_visible_item*( )

* *:linespacing*(_pixels_) +
_pixels_ = *:linespacing*( )


* *:marginleft*(_pixels_) +
_pixels_ = *:marginleft*( )


* *:margintop*(_pixels_) +
_pixels_ = *:margintop*( )


* _pathname_ = *:next*(_pathname_) +
_pathname_ = *:next_selected_item*(_pathname_) +
_pathname_ = *:next_visible_item*(_pathname_)

* *:openicon*(<<image, _image_>>) +
<<image, _image_>> = *:openicon*( )

* *:openchild_marginbottom*(_pixels_) +
_pixels_ = *:openchild_marginbottom*( )

* _pathname_ = *:prev*(_pathname_) +
_pathname_ = *:prev_selected_item*(_pathname_) +
_pathname_ = *:prev_visible_item*(_pathname_)

* *:remove*(_pathname_)

* *:root_label*(_name_)

* _name_ = *:root*( )


* *:scrollbar_size*(_pixels_) +
_pixels_ = *:scrollbar_size*( )

* *:show_item*([_pathname_], [_yoffset_])

* *:show_item_bottom*([_pathname_]) +
*:show_item_middle*([_pathname_]) +
*:show_item_top*([_pathname_])

* *:selectbox*(<<boxtype, _boxtype_>>) +
<<boxtype, _boxtype_>> = *:selectbox*( )

* *:selectmode*(<<treeselect, _treeselect_>>) +
<<treeselect, _treeselect_>> = *:selectmode*( )

* *:set_item_focus*([_pathname_])

* *:showcollapse*(_boolean_) +
_boolean_ = *:showcollapse*( )

* *:showroot*(_boolean_) +
_boolean_ = *:showroot*( )

* *:show_self*( )

* *:sortorder*(<<treesort, _treesort_>>) +
<<treesort, _treesort_>> = *:sortorder*( )

* *:usericon*(<<image, _image_>>) +
<<image, _image_>> = *:usericon*( )

* *:usericon_marginleft*(_pixels_) +
_pixels_ = *:usericon_marginleft*( )

* *:vposition*(_v_) +
_v_ = *:vposition*( )

* *:item_activate*(_pathname_)

* _pathname_  = *:item_child*(_pathname_, _index_)

* _n_ = *:item_children*(_pathname_)

* _boolean_ = *:item_close*(_pathname_, [_docallback_])

* *:item_deactivate*(_pathname_)

* _n_ = *:item_depth*(_pathname_)


* _boolean_ = *:item_deselect*([_pathname_], [_docallback_]) +
_boolean_ = *:item_deselect_all*([_pathname_], [_docallback_])

* *:item_display*([_pathname_])

* _boolean_ = *:item_displayed*([_pathname_])


* _index_  = *:item_find_child*(_pathname_, _name_) +
[small]#Returns _nil_ if the item _pathname_ has no child named _name_, otherwise
returns its index (1-based).#

* _h_ = *:item_h*(_pathname_)


* _boolean_ = *:item_has_children*(_pathname_) +
_boolean_ = *:item_is_active*(_pathname_) +
_boolean_ = *:item_is_activated*(_pathname_) +
_boolean_ = *:item_is_close*(_pathname_) +
_boolean_ = *:item_is_open*(_pathname_) +
_boolean_ = *:item_is_root*(_pathname_) +
_boolean_ = *:item_is_selected*(_pathname_) +
_boolean_ = *:item_is_visible*(_pathname_)

* *:item_label*(_pathname_, _label_) +
_label_ = *:item_label*(_pathname_)

* _x_ = *:item_label_x*(_pathname_) +
_y_ = *:item_label_y*(_pathname_) +
_w_ = *:item_label_w*(_pathname_) +
_h_ = *:item_label_h*(_pathname_) +


* *:item_labelbgcolor*([_pathname_], <<color, _color_>>) +
<<color, _color_>> = *:item_labelbgcolor*([_pathname_]) +
[small]#_pathname_=_nil_ to set/get the default color.#

* *:item_labelfgcolor*([_pathname_], <<color, _color_>>) +
<<color, _color_>> = *:item_labelfgcolor*([_pathname_]) +
[small]#_pathname_=_nil_ to set/get the default color.#

* *:item_labelcolor*: alias for *:item_labelfgcolor*.

* *:item_labelfont*([_pathname_], <<font, _font_>>) +
<<font, _font_>> = *:item_labelfont*([_pathname_]) +
[small]#_pathname_=_nil_ to set/get the default font.#


* *:item_labelsize*([_pathname_], _fontsize_) +
_fontsize_ = *:item_labelsize*([_pathname_]) +
[small]#_pathname_=_nil_ to set/get the default font size.#

* _boolean_ = *:item_open*(_pathname_, [_docallback_])


* _boolean_ = *:item_open_toggle*(_pathname_, [_docallback_])


* _pathname_ = *:item_parent*(_pathname_)


* *:item_show_self*(_pathname_, [_indent_])

* _boolean_ = *:item_select*([_pathname_], [_docallback_]) +
_boolean_ = *:item_select_all*([_pathname_], [_docallback_]) +
_boolean_ = *:item_select_only*([_pathname_], [_docallback_]) +
_boolean_ = *:item_select_toggle*([_pathname_], [_docallback_]) +

* *:item_swap_children*(_pathname_, _name~1~_, _name~2~_)

* *:item_user_data*(_pathname_, _val_) +
_val_ = *:item_user_data*(_pathname_) +
[small]#_val_: integer value to associate with the item (may be used to index
a Lua table containing more complex data).#


* *:item_usericon*(_pathname_, <<image, _image_>>) +
<<image, _image_>> = *:item_usericon*(_pathname_)

* *:item_visible*(_pathname_) +
_boolean_ = *:item_visible_r*(_pathname_)

* _w_ = *:item_w*(_pathname_)


* *:item_widget*(_pathname_, <<widget, _widget_>>) +
<<widget, _widget_>> = *:item_widget*(_pathname_)

* _x_ = *:item_x*(_pathname_) +
_y_ = *:item_y*(_pathname_)


