// should be included only in fldraw.cc

static void boxtypeDrawFunction(uchar n, int x, int y, int w, int h, Fl_Color color);

#define BOXTYPE_DRAW_FUNCTION_PROTO(n) \
static void boxtypeDrawFunction##n(int x, int y, int w, int h, Fl_Color color);

typedef struct {
    int            luaRef;
    Fl_Box_Draw_F* func;
} Boxtype_FunctionRef; // see table boxtype_FunctionRefs below

#define BOXTYPE_DRAW_FUNCTION_IMPL(n) \
static void boxtypeDrawFunction##n(int x, int y, int w, int h, Fl_Color color) \
    { \
    boxtypeDrawFunction(1##n - 1000, x, y, w, h, color); \
    } 

// Prototypes {
BOXTYPE_DRAW_FUNCTION_PROTO(000)
BOXTYPE_DRAW_FUNCTION_PROTO(001)
BOXTYPE_DRAW_FUNCTION_PROTO(002)
BOXTYPE_DRAW_FUNCTION_PROTO(003)
BOXTYPE_DRAW_FUNCTION_PROTO(004)
BOXTYPE_DRAW_FUNCTION_PROTO(005)
BOXTYPE_DRAW_FUNCTION_PROTO(006)
BOXTYPE_DRAW_FUNCTION_PROTO(007)
BOXTYPE_DRAW_FUNCTION_PROTO(008)
BOXTYPE_DRAW_FUNCTION_PROTO(009)
BOXTYPE_DRAW_FUNCTION_PROTO(010)
BOXTYPE_DRAW_FUNCTION_PROTO(011)
BOXTYPE_DRAW_FUNCTION_PROTO(012)
BOXTYPE_DRAW_FUNCTION_PROTO(013)
BOXTYPE_DRAW_FUNCTION_PROTO(014)
BOXTYPE_DRAW_FUNCTION_PROTO(015)
BOXTYPE_DRAW_FUNCTION_PROTO(016)
BOXTYPE_DRAW_FUNCTION_PROTO(017)
BOXTYPE_DRAW_FUNCTION_PROTO(018)
BOXTYPE_DRAW_FUNCTION_PROTO(019)
BOXTYPE_DRAW_FUNCTION_PROTO(020)
BOXTYPE_DRAW_FUNCTION_PROTO(021)
BOXTYPE_DRAW_FUNCTION_PROTO(022)
BOXTYPE_DRAW_FUNCTION_PROTO(023)
BOXTYPE_DRAW_FUNCTION_PROTO(024)
BOXTYPE_DRAW_FUNCTION_PROTO(025)
BOXTYPE_DRAW_FUNCTION_PROTO(026)
BOXTYPE_DRAW_FUNCTION_PROTO(027)
BOXTYPE_DRAW_FUNCTION_PROTO(028)
BOXTYPE_DRAW_FUNCTION_PROTO(029)
BOXTYPE_DRAW_FUNCTION_PROTO(030)
BOXTYPE_DRAW_FUNCTION_PROTO(031)
BOXTYPE_DRAW_FUNCTION_PROTO(032)
BOXTYPE_DRAW_FUNCTION_PROTO(033)
BOXTYPE_DRAW_FUNCTION_PROTO(034)
BOXTYPE_DRAW_FUNCTION_PROTO(035)
BOXTYPE_DRAW_FUNCTION_PROTO(036)
BOXTYPE_DRAW_FUNCTION_PROTO(037)
BOXTYPE_DRAW_FUNCTION_PROTO(038)
BOXTYPE_DRAW_FUNCTION_PROTO(039)
BOXTYPE_DRAW_FUNCTION_PROTO(040)
BOXTYPE_DRAW_FUNCTION_PROTO(041)
BOXTYPE_DRAW_FUNCTION_PROTO(042)
BOXTYPE_DRAW_FUNCTION_PROTO(043)
BOXTYPE_DRAW_FUNCTION_PROTO(044)
BOXTYPE_DRAW_FUNCTION_PROTO(045)
BOXTYPE_DRAW_FUNCTION_PROTO(046)
BOXTYPE_DRAW_FUNCTION_PROTO(047)
BOXTYPE_DRAW_FUNCTION_PROTO(048)
BOXTYPE_DRAW_FUNCTION_PROTO(049)
BOXTYPE_DRAW_FUNCTION_PROTO(050)
BOXTYPE_DRAW_FUNCTION_PROTO(051)
BOXTYPE_DRAW_FUNCTION_PROTO(052)
BOXTYPE_DRAW_FUNCTION_PROTO(053)
BOXTYPE_DRAW_FUNCTION_PROTO(054)
BOXTYPE_DRAW_FUNCTION_PROTO(055)
BOXTYPE_DRAW_FUNCTION_PROTO(056)
BOXTYPE_DRAW_FUNCTION_PROTO(057)
BOXTYPE_DRAW_FUNCTION_PROTO(058)
BOXTYPE_DRAW_FUNCTION_PROTO(059)
BOXTYPE_DRAW_FUNCTION_PROTO(060)
BOXTYPE_DRAW_FUNCTION_PROTO(061)
BOXTYPE_DRAW_FUNCTION_PROTO(062)
BOXTYPE_DRAW_FUNCTION_PROTO(063)
BOXTYPE_DRAW_FUNCTION_PROTO(064)
BOXTYPE_DRAW_FUNCTION_PROTO(065)
BOXTYPE_DRAW_FUNCTION_PROTO(066)
BOXTYPE_DRAW_FUNCTION_PROTO(067)
BOXTYPE_DRAW_FUNCTION_PROTO(068)
BOXTYPE_DRAW_FUNCTION_PROTO(069)
BOXTYPE_DRAW_FUNCTION_PROTO(070)
BOXTYPE_DRAW_FUNCTION_PROTO(071)
BOXTYPE_DRAW_FUNCTION_PROTO(072)
BOXTYPE_DRAW_FUNCTION_PROTO(073)
BOXTYPE_DRAW_FUNCTION_PROTO(074)
BOXTYPE_DRAW_FUNCTION_PROTO(075)
BOXTYPE_DRAW_FUNCTION_PROTO(076)
BOXTYPE_DRAW_FUNCTION_PROTO(077)
BOXTYPE_DRAW_FUNCTION_PROTO(078)
BOXTYPE_DRAW_FUNCTION_PROTO(079)
BOXTYPE_DRAW_FUNCTION_PROTO(080)
BOXTYPE_DRAW_FUNCTION_PROTO(081)
BOXTYPE_DRAW_FUNCTION_PROTO(082)
BOXTYPE_DRAW_FUNCTION_PROTO(083)
BOXTYPE_DRAW_FUNCTION_PROTO(084)
BOXTYPE_DRAW_FUNCTION_PROTO(085)
BOXTYPE_DRAW_FUNCTION_PROTO(086)
BOXTYPE_DRAW_FUNCTION_PROTO(087)
BOXTYPE_DRAW_FUNCTION_PROTO(088)
BOXTYPE_DRAW_FUNCTION_PROTO(089)
BOXTYPE_DRAW_FUNCTION_PROTO(090)
BOXTYPE_DRAW_FUNCTION_PROTO(091)
BOXTYPE_DRAW_FUNCTION_PROTO(092)
BOXTYPE_DRAW_FUNCTION_PROTO(093)
BOXTYPE_DRAW_FUNCTION_PROTO(094)
BOXTYPE_DRAW_FUNCTION_PROTO(095)
BOXTYPE_DRAW_FUNCTION_PROTO(096)
BOXTYPE_DRAW_FUNCTION_PROTO(097)
BOXTYPE_DRAW_FUNCTION_PROTO(098)
BOXTYPE_DRAW_FUNCTION_PROTO(099)
BOXTYPE_DRAW_FUNCTION_PROTO(100)
BOXTYPE_DRAW_FUNCTION_PROTO(101)
BOXTYPE_DRAW_FUNCTION_PROTO(102)
BOXTYPE_DRAW_FUNCTION_PROTO(103)
BOXTYPE_DRAW_FUNCTION_PROTO(104)
BOXTYPE_DRAW_FUNCTION_PROTO(105)
BOXTYPE_DRAW_FUNCTION_PROTO(106)
BOXTYPE_DRAW_FUNCTION_PROTO(107)
BOXTYPE_DRAW_FUNCTION_PROTO(108)
BOXTYPE_DRAW_FUNCTION_PROTO(109)
BOXTYPE_DRAW_FUNCTION_PROTO(110)
BOXTYPE_DRAW_FUNCTION_PROTO(111)
BOXTYPE_DRAW_FUNCTION_PROTO(112)
BOXTYPE_DRAW_FUNCTION_PROTO(113)
BOXTYPE_DRAW_FUNCTION_PROTO(114)
BOXTYPE_DRAW_FUNCTION_PROTO(115)
BOXTYPE_DRAW_FUNCTION_PROTO(116)
BOXTYPE_DRAW_FUNCTION_PROTO(117)
BOXTYPE_DRAW_FUNCTION_PROTO(118)
BOXTYPE_DRAW_FUNCTION_PROTO(119)
BOXTYPE_DRAW_FUNCTION_PROTO(120)
BOXTYPE_DRAW_FUNCTION_PROTO(121)
BOXTYPE_DRAW_FUNCTION_PROTO(122)
BOXTYPE_DRAW_FUNCTION_PROTO(123)
BOXTYPE_DRAW_FUNCTION_PROTO(124)
BOXTYPE_DRAW_FUNCTION_PROTO(125)
BOXTYPE_DRAW_FUNCTION_PROTO(126)
BOXTYPE_DRAW_FUNCTION_PROTO(127)
BOXTYPE_DRAW_FUNCTION_PROTO(128)
BOXTYPE_DRAW_FUNCTION_PROTO(129)
BOXTYPE_DRAW_FUNCTION_PROTO(130)
BOXTYPE_DRAW_FUNCTION_PROTO(131)
BOXTYPE_DRAW_FUNCTION_PROTO(132)
BOXTYPE_DRAW_FUNCTION_PROTO(133)
BOXTYPE_DRAW_FUNCTION_PROTO(134)
BOXTYPE_DRAW_FUNCTION_PROTO(135)
BOXTYPE_DRAW_FUNCTION_PROTO(136)
BOXTYPE_DRAW_FUNCTION_PROTO(137)
BOXTYPE_DRAW_FUNCTION_PROTO(138)
BOXTYPE_DRAW_FUNCTION_PROTO(139)
BOXTYPE_DRAW_FUNCTION_PROTO(140)
BOXTYPE_DRAW_FUNCTION_PROTO(141)
BOXTYPE_DRAW_FUNCTION_PROTO(142)
BOXTYPE_DRAW_FUNCTION_PROTO(143)
BOXTYPE_DRAW_FUNCTION_PROTO(144)
BOXTYPE_DRAW_FUNCTION_PROTO(145)
BOXTYPE_DRAW_FUNCTION_PROTO(146)
BOXTYPE_DRAW_FUNCTION_PROTO(147)
BOXTYPE_DRAW_FUNCTION_PROTO(148)
BOXTYPE_DRAW_FUNCTION_PROTO(149)
BOXTYPE_DRAW_FUNCTION_PROTO(150)
BOXTYPE_DRAW_FUNCTION_PROTO(151)
BOXTYPE_DRAW_FUNCTION_PROTO(152)
BOXTYPE_DRAW_FUNCTION_PROTO(153)
BOXTYPE_DRAW_FUNCTION_PROTO(154)
BOXTYPE_DRAW_FUNCTION_PROTO(155)
BOXTYPE_DRAW_FUNCTION_PROTO(156)
BOXTYPE_DRAW_FUNCTION_PROTO(157)
BOXTYPE_DRAW_FUNCTION_PROTO(158)
BOXTYPE_DRAW_FUNCTION_PROTO(159)
BOXTYPE_DRAW_FUNCTION_PROTO(160)
BOXTYPE_DRAW_FUNCTION_PROTO(161)
BOXTYPE_DRAW_FUNCTION_PROTO(162)
BOXTYPE_DRAW_FUNCTION_PROTO(163)
BOXTYPE_DRAW_FUNCTION_PROTO(164)
BOXTYPE_DRAW_FUNCTION_PROTO(165)
BOXTYPE_DRAW_FUNCTION_PROTO(166)
BOXTYPE_DRAW_FUNCTION_PROTO(167)
BOXTYPE_DRAW_FUNCTION_PROTO(168)
BOXTYPE_DRAW_FUNCTION_PROTO(169)
BOXTYPE_DRAW_FUNCTION_PROTO(170)
BOXTYPE_DRAW_FUNCTION_PROTO(171)
BOXTYPE_DRAW_FUNCTION_PROTO(172)
BOXTYPE_DRAW_FUNCTION_PROTO(173)
BOXTYPE_DRAW_FUNCTION_PROTO(174)
BOXTYPE_DRAW_FUNCTION_PROTO(175)
BOXTYPE_DRAW_FUNCTION_PROTO(176)
BOXTYPE_DRAW_FUNCTION_PROTO(177)
BOXTYPE_DRAW_FUNCTION_PROTO(178)
BOXTYPE_DRAW_FUNCTION_PROTO(179)
BOXTYPE_DRAW_FUNCTION_PROTO(180)
BOXTYPE_DRAW_FUNCTION_PROTO(181)
BOXTYPE_DRAW_FUNCTION_PROTO(182)
BOXTYPE_DRAW_FUNCTION_PROTO(183)
BOXTYPE_DRAW_FUNCTION_PROTO(184)
BOXTYPE_DRAW_FUNCTION_PROTO(185)
BOXTYPE_DRAW_FUNCTION_PROTO(186)
BOXTYPE_DRAW_FUNCTION_PROTO(187)
BOXTYPE_DRAW_FUNCTION_PROTO(188)
BOXTYPE_DRAW_FUNCTION_PROTO(189)
BOXTYPE_DRAW_FUNCTION_PROTO(190)
BOXTYPE_DRAW_FUNCTION_PROTO(191)
BOXTYPE_DRAW_FUNCTION_PROTO(192)
BOXTYPE_DRAW_FUNCTION_PROTO(193)
BOXTYPE_DRAW_FUNCTION_PROTO(194)
BOXTYPE_DRAW_FUNCTION_PROTO(195)
BOXTYPE_DRAW_FUNCTION_PROTO(196)
BOXTYPE_DRAW_FUNCTION_PROTO(197)
BOXTYPE_DRAW_FUNCTION_PROTO(198)
BOXTYPE_DRAW_FUNCTION_PROTO(199)
BOXTYPE_DRAW_FUNCTION_PROTO(200)
BOXTYPE_DRAW_FUNCTION_PROTO(201)
BOXTYPE_DRAW_FUNCTION_PROTO(202)
BOXTYPE_DRAW_FUNCTION_PROTO(203)
BOXTYPE_DRAW_FUNCTION_PROTO(204)
BOXTYPE_DRAW_FUNCTION_PROTO(205)
BOXTYPE_DRAW_FUNCTION_PROTO(206)
BOXTYPE_DRAW_FUNCTION_PROTO(207)
BOXTYPE_DRAW_FUNCTION_PROTO(208)
BOXTYPE_DRAW_FUNCTION_PROTO(209)
BOXTYPE_DRAW_FUNCTION_PROTO(210)
BOXTYPE_DRAW_FUNCTION_PROTO(211)
BOXTYPE_DRAW_FUNCTION_PROTO(212)
BOXTYPE_DRAW_FUNCTION_PROTO(213)
BOXTYPE_DRAW_FUNCTION_PROTO(214)
BOXTYPE_DRAW_FUNCTION_PROTO(215)
BOXTYPE_DRAW_FUNCTION_PROTO(216)
BOXTYPE_DRAW_FUNCTION_PROTO(217)
BOXTYPE_DRAW_FUNCTION_PROTO(218)
BOXTYPE_DRAW_FUNCTION_PROTO(219)
BOXTYPE_DRAW_FUNCTION_PROTO(220)
BOXTYPE_DRAW_FUNCTION_PROTO(221)
BOXTYPE_DRAW_FUNCTION_PROTO(222)
BOXTYPE_DRAW_FUNCTION_PROTO(223)
BOXTYPE_DRAW_FUNCTION_PROTO(224)
BOXTYPE_DRAW_FUNCTION_PROTO(225)
BOXTYPE_DRAW_FUNCTION_PROTO(226)
BOXTYPE_DRAW_FUNCTION_PROTO(227)
BOXTYPE_DRAW_FUNCTION_PROTO(228)
BOXTYPE_DRAW_FUNCTION_PROTO(229)
BOXTYPE_DRAW_FUNCTION_PROTO(230)
BOXTYPE_DRAW_FUNCTION_PROTO(231)
BOXTYPE_DRAW_FUNCTION_PROTO(232)
BOXTYPE_DRAW_FUNCTION_PROTO(233)
BOXTYPE_DRAW_FUNCTION_PROTO(234)
BOXTYPE_DRAW_FUNCTION_PROTO(235)
BOXTYPE_DRAW_FUNCTION_PROTO(236)
BOXTYPE_DRAW_FUNCTION_PROTO(237)
BOXTYPE_DRAW_FUNCTION_PROTO(238)
BOXTYPE_DRAW_FUNCTION_PROTO(239)
BOXTYPE_DRAW_FUNCTION_PROTO(240)
BOXTYPE_DRAW_FUNCTION_PROTO(241)
BOXTYPE_DRAW_FUNCTION_PROTO(242)
BOXTYPE_DRAW_FUNCTION_PROTO(243)
BOXTYPE_DRAW_FUNCTION_PROTO(244)
BOXTYPE_DRAW_FUNCTION_PROTO(245)
BOXTYPE_DRAW_FUNCTION_PROTO(246)
BOXTYPE_DRAW_FUNCTION_PROTO(247)
BOXTYPE_DRAW_FUNCTION_PROTO(248)
BOXTYPE_DRAW_FUNCTION_PROTO(249)
BOXTYPE_DRAW_FUNCTION_PROTO(250)
BOXTYPE_DRAW_FUNCTION_PROTO(251)
BOXTYPE_DRAW_FUNCTION_PROTO(252)
BOXTYPE_DRAW_FUNCTION_PROTO(253)
BOXTYPE_DRAW_FUNCTION_PROTO(254)
BOXTYPE_DRAW_FUNCTION_PROTO(255)
// } Prototypes

// ReferenceTable {
static Boxtype_FunctionRef boxtype_FunctionRefs[256] = {
    { LUA_NOREF, boxtypeDrawFunction000 },
    { LUA_NOREF, boxtypeDrawFunction001 },
    { LUA_NOREF, boxtypeDrawFunction002 },
    { LUA_NOREF, boxtypeDrawFunction003 },
    { LUA_NOREF, boxtypeDrawFunction004 },
    { LUA_NOREF, boxtypeDrawFunction005 },
    { LUA_NOREF, boxtypeDrawFunction006 },
    { LUA_NOREF, boxtypeDrawFunction007 },
    { LUA_NOREF, boxtypeDrawFunction008 },
    { LUA_NOREF, boxtypeDrawFunction009 },
    { LUA_NOREF, boxtypeDrawFunction010 },
    { LUA_NOREF, boxtypeDrawFunction011 },
    { LUA_NOREF, boxtypeDrawFunction012 },
    { LUA_NOREF, boxtypeDrawFunction013 },
    { LUA_NOREF, boxtypeDrawFunction014 },
    { LUA_NOREF, boxtypeDrawFunction015 },
    { LUA_NOREF, boxtypeDrawFunction016 },
    { LUA_NOREF, boxtypeDrawFunction017 },
    { LUA_NOREF, boxtypeDrawFunction018 },
    { LUA_NOREF, boxtypeDrawFunction019 },
    { LUA_NOREF, boxtypeDrawFunction020 },
    { LUA_NOREF, boxtypeDrawFunction021 },
    { LUA_NOREF, boxtypeDrawFunction022 },
    { LUA_NOREF, boxtypeDrawFunction023 },
    { LUA_NOREF, boxtypeDrawFunction024 },
    { LUA_NOREF, boxtypeDrawFunction025 },
    { LUA_NOREF, boxtypeDrawFunction026 },
    { LUA_NOREF, boxtypeDrawFunction027 },
    { LUA_NOREF, boxtypeDrawFunction028 },
    { LUA_NOREF, boxtypeDrawFunction029 },
    { LUA_NOREF, boxtypeDrawFunction030 },
    { LUA_NOREF, boxtypeDrawFunction031 },
    { LUA_NOREF, boxtypeDrawFunction032 },
    { LUA_NOREF, boxtypeDrawFunction033 },
    { LUA_NOREF, boxtypeDrawFunction034 },
    { LUA_NOREF, boxtypeDrawFunction035 },
    { LUA_NOREF, boxtypeDrawFunction036 },
    { LUA_NOREF, boxtypeDrawFunction037 },
    { LUA_NOREF, boxtypeDrawFunction038 },
    { LUA_NOREF, boxtypeDrawFunction039 },
    { LUA_NOREF, boxtypeDrawFunction040 },
    { LUA_NOREF, boxtypeDrawFunction041 },
    { LUA_NOREF, boxtypeDrawFunction042 },
    { LUA_NOREF, boxtypeDrawFunction043 },
    { LUA_NOREF, boxtypeDrawFunction044 },
    { LUA_NOREF, boxtypeDrawFunction045 },
    { LUA_NOREF, boxtypeDrawFunction046 },
    { LUA_NOREF, boxtypeDrawFunction047 },
    { LUA_NOREF, boxtypeDrawFunction048 },
    { LUA_NOREF, boxtypeDrawFunction049 },
    { LUA_NOREF, boxtypeDrawFunction050 },
    { LUA_NOREF, boxtypeDrawFunction051 },
    { LUA_NOREF, boxtypeDrawFunction052 },
    { LUA_NOREF, boxtypeDrawFunction053 },
    { LUA_NOREF, boxtypeDrawFunction054 },
    { LUA_NOREF, boxtypeDrawFunction055 },
    { LUA_NOREF, boxtypeDrawFunction056 },
    { LUA_NOREF, boxtypeDrawFunction057 },
    { LUA_NOREF, boxtypeDrawFunction058 },
    { LUA_NOREF, boxtypeDrawFunction059 },
    { LUA_NOREF, boxtypeDrawFunction060 },
    { LUA_NOREF, boxtypeDrawFunction061 },
    { LUA_NOREF, boxtypeDrawFunction062 },
    { LUA_NOREF, boxtypeDrawFunction063 },
    { LUA_NOREF, boxtypeDrawFunction064 },
    { LUA_NOREF, boxtypeDrawFunction065 },
    { LUA_NOREF, boxtypeDrawFunction066 },
    { LUA_NOREF, boxtypeDrawFunction067 },
    { LUA_NOREF, boxtypeDrawFunction068 },
    { LUA_NOREF, boxtypeDrawFunction069 },
    { LUA_NOREF, boxtypeDrawFunction070 },
    { LUA_NOREF, boxtypeDrawFunction071 },
    { LUA_NOREF, boxtypeDrawFunction072 },
    { LUA_NOREF, boxtypeDrawFunction073 },
    { LUA_NOREF, boxtypeDrawFunction074 },
    { LUA_NOREF, boxtypeDrawFunction075 },
    { LUA_NOREF, boxtypeDrawFunction076 },
    { LUA_NOREF, boxtypeDrawFunction077 },
    { LUA_NOREF, boxtypeDrawFunction078 },
    { LUA_NOREF, boxtypeDrawFunction079 },
    { LUA_NOREF, boxtypeDrawFunction080 },
    { LUA_NOREF, boxtypeDrawFunction081 },
    { LUA_NOREF, boxtypeDrawFunction082 },
    { LUA_NOREF, boxtypeDrawFunction083 },
    { LUA_NOREF, boxtypeDrawFunction084 },
    { LUA_NOREF, boxtypeDrawFunction085 },
    { LUA_NOREF, boxtypeDrawFunction086 },
    { LUA_NOREF, boxtypeDrawFunction087 },
    { LUA_NOREF, boxtypeDrawFunction088 },
    { LUA_NOREF, boxtypeDrawFunction089 },
    { LUA_NOREF, boxtypeDrawFunction090 },
    { LUA_NOREF, boxtypeDrawFunction091 },
    { LUA_NOREF, boxtypeDrawFunction092 },
    { LUA_NOREF, boxtypeDrawFunction093 },
    { LUA_NOREF, boxtypeDrawFunction094 },
    { LUA_NOREF, boxtypeDrawFunction095 },
    { LUA_NOREF, boxtypeDrawFunction096 },
    { LUA_NOREF, boxtypeDrawFunction097 },
    { LUA_NOREF, boxtypeDrawFunction098 },
    { LUA_NOREF, boxtypeDrawFunction099 },
    { LUA_NOREF, boxtypeDrawFunction100 },
    { LUA_NOREF, boxtypeDrawFunction101 },
    { LUA_NOREF, boxtypeDrawFunction102 },
    { LUA_NOREF, boxtypeDrawFunction103 },
    { LUA_NOREF, boxtypeDrawFunction104 },
    { LUA_NOREF, boxtypeDrawFunction105 },
    { LUA_NOREF, boxtypeDrawFunction106 },
    { LUA_NOREF, boxtypeDrawFunction107 },
    { LUA_NOREF, boxtypeDrawFunction108 },
    { LUA_NOREF, boxtypeDrawFunction109 },
    { LUA_NOREF, boxtypeDrawFunction110 },
    { LUA_NOREF, boxtypeDrawFunction111 },
    { LUA_NOREF, boxtypeDrawFunction112 },
    { LUA_NOREF, boxtypeDrawFunction113 },
    { LUA_NOREF, boxtypeDrawFunction114 },
    { LUA_NOREF, boxtypeDrawFunction115 },
    { LUA_NOREF, boxtypeDrawFunction116 },
    { LUA_NOREF, boxtypeDrawFunction117 },
    { LUA_NOREF, boxtypeDrawFunction118 },
    { LUA_NOREF, boxtypeDrawFunction119 },
    { LUA_NOREF, boxtypeDrawFunction120 },
    { LUA_NOREF, boxtypeDrawFunction121 },
    { LUA_NOREF, boxtypeDrawFunction122 },
    { LUA_NOREF, boxtypeDrawFunction123 },
    { LUA_NOREF, boxtypeDrawFunction124 },
    { LUA_NOREF, boxtypeDrawFunction125 },
    { LUA_NOREF, boxtypeDrawFunction126 },
    { LUA_NOREF, boxtypeDrawFunction127 },
    { LUA_NOREF, boxtypeDrawFunction128 },
    { LUA_NOREF, boxtypeDrawFunction129 },
    { LUA_NOREF, boxtypeDrawFunction130 },
    { LUA_NOREF, boxtypeDrawFunction131 },
    { LUA_NOREF, boxtypeDrawFunction132 },
    { LUA_NOREF, boxtypeDrawFunction133 },
    { LUA_NOREF, boxtypeDrawFunction134 },
    { LUA_NOREF, boxtypeDrawFunction135 },
    { LUA_NOREF, boxtypeDrawFunction136 },
    { LUA_NOREF, boxtypeDrawFunction137 },
    { LUA_NOREF, boxtypeDrawFunction138 },
    { LUA_NOREF, boxtypeDrawFunction139 },
    { LUA_NOREF, boxtypeDrawFunction140 },
    { LUA_NOREF, boxtypeDrawFunction141 },
    { LUA_NOREF, boxtypeDrawFunction142 },
    { LUA_NOREF, boxtypeDrawFunction143 },
    { LUA_NOREF, boxtypeDrawFunction144 },
    { LUA_NOREF, boxtypeDrawFunction145 },
    { LUA_NOREF, boxtypeDrawFunction146 },
    { LUA_NOREF, boxtypeDrawFunction147 },
    { LUA_NOREF, boxtypeDrawFunction148 },
    { LUA_NOREF, boxtypeDrawFunction149 },
    { LUA_NOREF, boxtypeDrawFunction150 },
    { LUA_NOREF, boxtypeDrawFunction151 },
    { LUA_NOREF, boxtypeDrawFunction152 },
    { LUA_NOREF, boxtypeDrawFunction153 },
    { LUA_NOREF, boxtypeDrawFunction154 },
    { LUA_NOREF, boxtypeDrawFunction155 },
    { LUA_NOREF, boxtypeDrawFunction156 },
    { LUA_NOREF, boxtypeDrawFunction157 },
    { LUA_NOREF, boxtypeDrawFunction158 },
    { LUA_NOREF, boxtypeDrawFunction159 },
    { LUA_NOREF, boxtypeDrawFunction160 },
    { LUA_NOREF, boxtypeDrawFunction161 },
    { LUA_NOREF, boxtypeDrawFunction162 },
    { LUA_NOREF, boxtypeDrawFunction163 },
    { LUA_NOREF, boxtypeDrawFunction164 },
    { LUA_NOREF, boxtypeDrawFunction165 },
    { LUA_NOREF, boxtypeDrawFunction166 },
    { LUA_NOREF, boxtypeDrawFunction167 },
    { LUA_NOREF, boxtypeDrawFunction168 },
    { LUA_NOREF, boxtypeDrawFunction169 },
    { LUA_NOREF, boxtypeDrawFunction170 },
    { LUA_NOREF, boxtypeDrawFunction171 },
    { LUA_NOREF, boxtypeDrawFunction172 },
    { LUA_NOREF, boxtypeDrawFunction173 },
    { LUA_NOREF, boxtypeDrawFunction174 },
    { LUA_NOREF, boxtypeDrawFunction175 },
    { LUA_NOREF, boxtypeDrawFunction176 },
    { LUA_NOREF, boxtypeDrawFunction177 },
    { LUA_NOREF, boxtypeDrawFunction178 },
    { LUA_NOREF, boxtypeDrawFunction179 },
    { LUA_NOREF, boxtypeDrawFunction180 },
    { LUA_NOREF, boxtypeDrawFunction181 },
    { LUA_NOREF, boxtypeDrawFunction182 },
    { LUA_NOREF, boxtypeDrawFunction183 },
    { LUA_NOREF, boxtypeDrawFunction184 },
    { LUA_NOREF, boxtypeDrawFunction185 },
    { LUA_NOREF, boxtypeDrawFunction186 },
    { LUA_NOREF, boxtypeDrawFunction187 },
    { LUA_NOREF, boxtypeDrawFunction188 },
    { LUA_NOREF, boxtypeDrawFunction189 },
    { LUA_NOREF, boxtypeDrawFunction190 },
    { LUA_NOREF, boxtypeDrawFunction191 },
    { LUA_NOREF, boxtypeDrawFunction192 },
    { LUA_NOREF, boxtypeDrawFunction193 },
    { LUA_NOREF, boxtypeDrawFunction194 },
    { LUA_NOREF, boxtypeDrawFunction195 },
    { LUA_NOREF, boxtypeDrawFunction196 },
    { LUA_NOREF, boxtypeDrawFunction197 },
    { LUA_NOREF, boxtypeDrawFunction198 },
    { LUA_NOREF, boxtypeDrawFunction199 },
    { LUA_NOREF, boxtypeDrawFunction200 },
    { LUA_NOREF, boxtypeDrawFunction201 },
    { LUA_NOREF, boxtypeDrawFunction202 },
    { LUA_NOREF, boxtypeDrawFunction203 },
    { LUA_NOREF, boxtypeDrawFunction204 },
    { LUA_NOREF, boxtypeDrawFunction205 },
    { LUA_NOREF, boxtypeDrawFunction206 },
    { LUA_NOREF, boxtypeDrawFunction207 },
    { LUA_NOREF, boxtypeDrawFunction208 },
    { LUA_NOREF, boxtypeDrawFunction209 },
    { LUA_NOREF, boxtypeDrawFunction210 },
    { LUA_NOREF, boxtypeDrawFunction211 },
    { LUA_NOREF, boxtypeDrawFunction212 },
    { LUA_NOREF, boxtypeDrawFunction213 },
    { LUA_NOREF, boxtypeDrawFunction214 },
    { LUA_NOREF, boxtypeDrawFunction215 },
    { LUA_NOREF, boxtypeDrawFunction216 },
    { LUA_NOREF, boxtypeDrawFunction217 },
    { LUA_NOREF, boxtypeDrawFunction218 },
    { LUA_NOREF, boxtypeDrawFunction219 },
    { LUA_NOREF, boxtypeDrawFunction220 },
    { LUA_NOREF, boxtypeDrawFunction221 },
    { LUA_NOREF, boxtypeDrawFunction222 },
    { LUA_NOREF, boxtypeDrawFunction223 },
    { LUA_NOREF, boxtypeDrawFunction224 },
    { LUA_NOREF, boxtypeDrawFunction225 },
    { LUA_NOREF, boxtypeDrawFunction226 },
    { LUA_NOREF, boxtypeDrawFunction227 },
    { LUA_NOREF, boxtypeDrawFunction228 },
    { LUA_NOREF, boxtypeDrawFunction229 },
    { LUA_NOREF, boxtypeDrawFunction230 },
    { LUA_NOREF, boxtypeDrawFunction231 },
    { LUA_NOREF, boxtypeDrawFunction232 },
    { LUA_NOREF, boxtypeDrawFunction233 },
    { LUA_NOREF, boxtypeDrawFunction234 },
    { LUA_NOREF, boxtypeDrawFunction235 },
    { LUA_NOREF, boxtypeDrawFunction236 },
    { LUA_NOREF, boxtypeDrawFunction237 },
    { LUA_NOREF, boxtypeDrawFunction238 },
    { LUA_NOREF, boxtypeDrawFunction239 },
    { LUA_NOREF, boxtypeDrawFunction240 },
    { LUA_NOREF, boxtypeDrawFunction241 },
    { LUA_NOREF, boxtypeDrawFunction242 },
    { LUA_NOREF, boxtypeDrawFunction243 },
    { LUA_NOREF, boxtypeDrawFunction244 },
    { LUA_NOREF, boxtypeDrawFunction245 },
    { LUA_NOREF, boxtypeDrawFunction246 },
    { LUA_NOREF, boxtypeDrawFunction247 },
    { LUA_NOREF, boxtypeDrawFunction248 },
    { LUA_NOREF, boxtypeDrawFunction249 },
    { LUA_NOREF, boxtypeDrawFunction250 },
    { LUA_NOREF, boxtypeDrawFunction251 },
    { LUA_NOREF, boxtypeDrawFunction252 },
    { LUA_NOREF, boxtypeDrawFunction253 },
    { LUA_NOREF, boxtypeDrawFunction254 },
    { LUA_NOREF, boxtypeDrawFunction255 }
}; // } ReferenceTable

// Implementations {
BOXTYPE_DRAW_FUNCTION_IMPL(000)
BOXTYPE_DRAW_FUNCTION_IMPL(001)
BOXTYPE_DRAW_FUNCTION_IMPL(002)
BOXTYPE_DRAW_FUNCTION_IMPL(003)
BOXTYPE_DRAW_FUNCTION_IMPL(004)
BOXTYPE_DRAW_FUNCTION_IMPL(005)
BOXTYPE_DRAW_FUNCTION_IMPL(006)
BOXTYPE_DRAW_FUNCTION_IMPL(007)
BOXTYPE_DRAW_FUNCTION_IMPL(008)
BOXTYPE_DRAW_FUNCTION_IMPL(009)
BOXTYPE_DRAW_FUNCTION_IMPL(010)
BOXTYPE_DRAW_FUNCTION_IMPL(011)
BOXTYPE_DRAW_FUNCTION_IMPL(012)
BOXTYPE_DRAW_FUNCTION_IMPL(013)
BOXTYPE_DRAW_FUNCTION_IMPL(014)
BOXTYPE_DRAW_FUNCTION_IMPL(015)
BOXTYPE_DRAW_FUNCTION_IMPL(016)
BOXTYPE_DRAW_FUNCTION_IMPL(017)
BOXTYPE_DRAW_FUNCTION_IMPL(018)
BOXTYPE_DRAW_FUNCTION_IMPL(019)
BOXTYPE_DRAW_FUNCTION_IMPL(020)
BOXTYPE_DRAW_FUNCTION_IMPL(021)
BOXTYPE_DRAW_FUNCTION_IMPL(022)
BOXTYPE_DRAW_FUNCTION_IMPL(023)
BOXTYPE_DRAW_FUNCTION_IMPL(024)
BOXTYPE_DRAW_FUNCTION_IMPL(025)
BOXTYPE_DRAW_FUNCTION_IMPL(026)
BOXTYPE_DRAW_FUNCTION_IMPL(027)
BOXTYPE_DRAW_FUNCTION_IMPL(028)
BOXTYPE_DRAW_FUNCTION_IMPL(029)
BOXTYPE_DRAW_FUNCTION_IMPL(030)
BOXTYPE_DRAW_FUNCTION_IMPL(031)
BOXTYPE_DRAW_FUNCTION_IMPL(032)
BOXTYPE_DRAW_FUNCTION_IMPL(033)
BOXTYPE_DRAW_FUNCTION_IMPL(034)
BOXTYPE_DRAW_FUNCTION_IMPL(035)
BOXTYPE_DRAW_FUNCTION_IMPL(036)
BOXTYPE_DRAW_FUNCTION_IMPL(037)
BOXTYPE_DRAW_FUNCTION_IMPL(038)
BOXTYPE_DRAW_FUNCTION_IMPL(039)
BOXTYPE_DRAW_FUNCTION_IMPL(040)
BOXTYPE_DRAW_FUNCTION_IMPL(041)
BOXTYPE_DRAW_FUNCTION_IMPL(042)
BOXTYPE_DRAW_FUNCTION_IMPL(043)
BOXTYPE_DRAW_FUNCTION_IMPL(044)
BOXTYPE_DRAW_FUNCTION_IMPL(045)
BOXTYPE_DRAW_FUNCTION_IMPL(046)
BOXTYPE_DRAW_FUNCTION_IMPL(047)
BOXTYPE_DRAW_FUNCTION_IMPL(048)
BOXTYPE_DRAW_FUNCTION_IMPL(049)
BOXTYPE_DRAW_FUNCTION_IMPL(050)
BOXTYPE_DRAW_FUNCTION_IMPL(051)
BOXTYPE_DRAW_FUNCTION_IMPL(052)
BOXTYPE_DRAW_FUNCTION_IMPL(053)
BOXTYPE_DRAW_FUNCTION_IMPL(054)
BOXTYPE_DRAW_FUNCTION_IMPL(055)
BOXTYPE_DRAW_FUNCTION_IMPL(056)
BOXTYPE_DRAW_FUNCTION_IMPL(057)
BOXTYPE_DRAW_FUNCTION_IMPL(058)
BOXTYPE_DRAW_FUNCTION_IMPL(059)
BOXTYPE_DRAW_FUNCTION_IMPL(060)
BOXTYPE_DRAW_FUNCTION_IMPL(061)
BOXTYPE_DRAW_FUNCTION_IMPL(062)
BOXTYPE_DRAW_FUNCTION_IMPL(063)
BOXTYPE_DRAW_FUNCTION_IMPL(064)
BOXTYPE_DRAW_FUNCTION_IMPL(065)
BOXTYPE_DRAW_FUNCTION_IMPL(066)
BOXTYPE_DRAW_FUNCTION_IMPL(067)
BOXTYPE_DRAW_FUNCTION_IMPL(068)
BOXTYPE_DRAW_FUNCTION_IMPL(069)
BOXTYPE_DRAW_FUNCTION_IMPL(070)
BOXTYPE_DRAW_FUNCTION_IMPL(071)
BOXTYPE_DRAW_FUNCTION_IMPL(072)
BOXTYPE_DRAW_FUNCTION_IMPL(073)
BOXTYPE_DRAW_FUNCTION_IMPL(074)
BOXTYPE_DRAW_FUNCTION_IMPL(075)
BOXTYPE_DRAW_FUNCTION_IMPL(076)
BOXTYPE_DRAW_FUNCTION_IMPL(077)
BOXTYPE_DRAW_FUNCTION_IMPL(078)
BOXTYPE_DRAW_FUNCTION_IMPL(079)
BOXTYPE_DRAW_FUNCTION_IMPL(080)
BOXTYPE_DRAW_FUNCTION_IMPL(081)
BOXTYPE_DRAW_FUNCTION_IMPL(082)
BOXTYPE_DRAW_FUNCTION_IMPL(083)
BOXTYPE_DRAW_FUNCTION_IMPL(084)
BOXTYPE_DRAW_FUNCTION_IMPL(085)
BOXTYPE_DRAW_FUNCTION_IMPL(086)
BOXTYPE_DRAW_FUNCTION_IMPL(087)
BOXTYPE_DRAW_FUNCTION_IMPL(088)
BOXTYPE_DRAW_FUNCTION_IMPL(089)
BOXTYPE_DRAW_FUNCTION_IMPL(090)
BOXTYPE_DRAW_FUNCTION_IMPL(091)
BOXTYPE_DRAW_FUNCTION_IMPL(092)
BOXTYPE_DRAW_FUNCTION_IMPL(093)
BOXTYPE_DRAW_FUNCTION_IMPL(094)
BOXTYPE_DRAW_FUNCTION_IMPL(095)
BOXTYPE_DRAW_FUNCTION_IMPL(096)
BOXTYPE_DRAW_FUNCTION_IMPL(097)
BOXTYPE_DRAW_FUNCTION_IMPL(098)
BOXTYPE_DRAW_FUNCTION_IMPL(099)
BOXTYPE_DRAW_FUNCTION_IMPL(100)
BOXTYPE_DRAW_FUNCTION_IMPL(101)
BOXTYPE_DRAW_FUNCTION_IMPL(102)
BOXTYPE_DRAW_FUNCTION_IMPL(103)
BOXTYPE_DRAW_FUNCTION_IMPL(104)
BOXTYPE_DRAW_FUNCTION_IMPL(105)
BOXTYPE_DRAW_FUNCTION_IMPL(106)
BOXTYPE_DRAW_FUNCTION_IMPL(107)
BOXTYPE_DRAW_FUNCTION_IMPL(108)
BOXTYPE_DRAW_FUNCTION_IMPL(109)
BOXTYPE_DRAW_FUNCTION_IMPL(110)
BOXTYPE_DRAW_FUNCTION_IMPL(111)
BOXTYPE_DRAW_FUNCTION_IMPL(112)
BOXTYPE_DRAW_FUNCTION_IMPL(113)
BOXTYPE_DRAW_FUNCTION_IMPL(114)
BOXTYPE_DRAW_FUNCTION_IMPL(115)
BOXTYPE_DRAW_FUNCTION_IMPL(116)
BOXTYPE_DRAW_FUNCTION_IMPL(117)
BOXTYPE_DRAW_FUNCTION_IMPL(118)
BOXTYPE_DRAW_FUNCTION_IMPL(119)
BOXTYPE_DRAW_FUNCTION_IMPL(120)
BOXTYPE_DRAW_FUNCTION_IMPL(121)
BOXTYPE_DRAW_FUNCTION_IMPL(122)
BOXTYPE_DRAW_FUNCTION_IMPL(123)
BOXTYPE_DRAW_FUNCTION_IMPL(124)
BOXTYPE_DRAW_FUNCTION_IMPL(125)
BOXTYPE_DRAW_FUNCTION_IMPL(126)
BOXTYPE_DRAW_FUNCTION_IMPL(127)
BOXTYPE_DRAW_FUNCTION_IMPL(128)
BOXTYPE_DRAW_FUNCTION_IMPL(129)
BOXTYPE_DRAW_FUNCTION_IMPL(130)
BOXTYPE_DRAW_FUNCTION_IMPL(131)
BOXTYPE_DRAW_FUNCTION_IMPL(132)
BOXTYPE_DRAW_FUNCTION_IMPL(133)
BOXTYPE_DRAW_FUNCTION_IMPL(134)
BOXTYPE_DRAW_FUNCTION_IMPL(135)
BOXTYPE_DRAW_FUNCTION_IMPL(136)
BOXTYPE_DRAW_FUNCTION_IMPL(137)
BOXTYPE_DRAW_FUNCTION_IMPL(138)
BOXTYPE_DRAW_FUNCTION_IMPL(139)
BOXTYPE_DRAW_FUNCTION_IMPL(140)
BOXTYPE_DRAW_FUNCTION_IMPL(141)
BOXTYPE_DRAW_FUNCTION_IMPL(142)
BOXTYPE_DRAW_FUNCTION_IMPL(143)
BOXTYPE_DRAW_FUNCTION_IMPL(144)
BOXTYPE_DRAW_FUNCTION_IMPL(145)
BOXTYPE_DRAW_FUNCTION_IMPL(146)
BOXTYPE_DRAW_FUNCTION_IMPL(147)
BOXTYPE_DRAW_FUNCTION_IMPL(148)
BOXTYPE_DRAW_FUNCTION_IMPL(149)
BOXTYPE_DRAW_FUNCTION_IMPL(150)
BOXTYPE_DRAW_FUNCTION_IMPL(151)
BOXTYPE_DRAW_FUNCTION_IMPL(152)
BOXTYPE_DRAW_FUNCTION_IMPL(153)
BOXTYPE_DRAW_FUNCTION_IMPL(154)
BOXTYPE_DRAW_FUNCTION_IMPL(155)
BOXTYPE_DRAW_FUNCTION_IMPL(156)
BOXTYPE_DRAW_FUNCTION_IMPL(157)
BOXTYPE_DRAW_FUNCTION_IMPL(158)
BOXTYPE_DRAW_FUNCTION_IMPL(159)
BOXTYPE_DRAW_FUNCTION_IMPL(160)
BOXTYPE_DRAW_FUNCTION_IMPL(161)
BOXTYPE_DRAW_FUNCTION_IMPL(162)
BOXTYPE_DRAW_FUNCTION_IMPL(163)
BOXTYPE_DRAW_FUNCTION_IMPL(164)
BOXTYPE_DRAW_FUNCTION_IMPL(165)
BOXTYPE_DRAW_FUNCTION_IMPL(166)
BOXTYPE_DRAW_FUNCTION_IMPL(167)
BOXTYPE_DRAW_FUNCTION_IMPL(168)
BOXTYPE_DRAW_FUNCTION_IMPL(169)
BOXTYPE_DRAW_FUNCTION_IMPL(170)
BOXTYPE_DRAW_FUNCTION_IMPL(171)
BOXTYPE_DRAW_FUNCTION_IMPL(172)
BOXTYPE_DRAW_FUNCTION_IMPL(173)
BOXTYPE_DRAW_FUNCTION_IMPL(174)
BOXTYPE_DRAW_FUNCTION_IMPL(175)
BOXTYPE_DRAW_FUNCTION_IMPL(176)
BOXTYPE_DRAW_FUNCTION_IMPL(177)
BOXTYPE_DRAW_FUNCTION_IMPL(178)
BOXTYPE_DRAW_FUNCTION_IMPL(179)
BOXTYPE_DRAW_FUNCTION_IMPL(180)
BOXTYPE_DRAW_FUNCTION_IMPL(181)
BOXTYPE_DRAW_FUNCTION_IMPL(182)
BOXTYPE_DRAW_FUNCTION_IMPL(183)
BOXTYPE_DRAW_FUNCTION_IMPL(184)
BOXTYPE_DRAW_FUNCTION_IMPL(185)
BOXTYPE_DRAW_FUNCTION_IMPL(186)
BOXTYPE_DRAW_FUNCTION_IMPL(187)
BOXTYPE_DRAW_FUNCTION_IMPL(188)
BOXTYPE_DRAW_FUNCTION_IMPL(189)
BOXTYPE_DRAW_FUNCTION_IMPL(190)
BOXTYPE_DRAW_FUNCTION_IMPL(191)
BOXTYPE_DRAW_FUNCTION_IMPL(192)
BOXTYPE_DRAW_FUNCTION_IMPL(193)
BOXTYPE_DRAW_FUNCTION_IMPL(194)
BOXTYPE_DRAW_FUNCTION_IMPL(195)
BOXTYPE_DRAW_FUNCTION_IMPL(196)
BOXTYPE_DRAW_FUNCTION_IMPL(197)
BOXTYPE_DRAW_FUNCTION_IMPL(198)
BOXTYPE_DRAW_FUNCTION_IMPL(199)
BOXTYPE_DRAW_FUNCTION_IMPL(200)
BOXTYPE_DRAW_FUNCTION_IMPL(201)
BOXTYPE_DRAW_FUNCTION_IMPL(202)
BOXTYPE_DRAW_FUNCTION_IMPL(203)
BOXTYPE_DRAW_FUNCTION_IMPL(204)
BOXTYPE_DRAW_FUNCTION_IMPL(205)
BOXTYPE_DRAW_FUNCTION_IMPL(206)
BOXTYPE_DRAW_FUNCTION_IMPL(207)
BOXTYPE_DRAW_FUNCTION_IMPL(208)
BOXTYPE_DRAW_FUNCTION_IMPL(209)
BOXTYPE_DRAW_FUNCTION_IMPL(210)
BOXTYPE_DRAW_FUNCTION_IMPL(211)
BOXTYPE_DRAW_FUNCTION_IMPL(212)
BOXTYPE_DRAW_FUNCTION_IMPL(213)
BOXTYPE_DRAW_FUNCTION_IMPL(214)
BOXTYPE_DRAW_FUNCTION_IMPL(215)
BOXTYPE_DRAW_FUNCTION_IMPL(216)
BOXTYPE_DRAW_FUNCTION_IMPL(217)
BOXTYPE_DRAW_FUNCTION_IMPL(218)
BOXTYPE_DRAW_FUNCTION_IMPL(219)
BOXTYPE_DRAW_FUNCTION_IMPL(220)
BOXTYPE_DRAW_FUNCTION_IMPL(221)
BOXTYPE_DRAW_FUNCTION_IMPL(222)
BOXTYPE_DRAW_FUNCTION_IMPL(223)
BOXTYPE_DRAW_FUNCTION_IMPL(224)
BOXTYPE_DRAW_FUNCTION_IMPL(225)
BOXTYPE_DRAW_FUNCTION_IMPL(226)
BOXTYPE_DRAW_FUNCTION_IMPL(227)
BOXTYPE_DRAW_FUNCTION_IMPL(228)
BOXTYPE_DRAW_FUNCTION_IMPL(229)
BOXTYPE_DRAW_FUNCTION_IMPL(230)
BOXTYPE_DRAW_FUNCTION_IMPL(231)
BOXTYPE_DRAW_FUNCTION_IMPL(232)
BOXTYPE_DRAW_FUNCTION_IMPL(233)
BOXTYPE_DRAW_FUNCTION_IMPL(234)
BOXTYPE_DRAW_FUNCTION_IMPL(235)
BOXTYPE_DRAW_FUNCTION_IMPL(236)
BOXTYPE_DRAW_FUNCTION_IMPL(237)
BOXTYPE_DRAW_FUNCTION_IMPL(238)
BOXTYPE_DRAW_FUNCTION_IMPL(239)
BOXTYPE_DRAW_FUNCTION_IMPL(240)
BOXTYPE_DRAW_FUNCTION_IMPL(241)
BOXTYPE_DRAW_FUNCTION_IMPL(242)
BOXTYPE_DRAW_FUNCTION_IMPL(243)
BOXTYPE_DRAW_FUNCTION_IMPL(244)
BOXTYPE_DRAW_FUNCTION_IMPL(245)
BOXTYPE_DRAW_FUNCTION_IMPL(246)
BOXTYPE_DRAW_FUNCTION_IMPL(247)
BOXTYPE_DRAW_FUNCTION_IMPL(248)
BOXTYPE_DRAW_FUNCTION_IMPL(249)
BOXTYPE_DRAW_FUNCTION_IMPL(250)
BOXTYPE_DRAW_FUNCTION_IMPL(251)
BOXTYPE_DRAW_FUNCTION_IMPL(252)
BOXTYPE_DRAW_FUNCTION_IMPL(253)
BOXTYPE_DRAW_FUNCTION_IMPL(254)
BOXTYPE_DRAW_FUNCTION_IMPL(255)
// } Implementations
